### ISSUE TITLE
Fatal error when Instagram API returns null - crashes page and admin page

### ISSUE THREAD

**Issue by gorelegacy** [scaramangagency/craftagram#91]
The plugin throws a fatal PHP error that crashes the page the feed is on  when the Instagram API returns null. This occurs when calling property_exists() on a null value returned from getInstagramProfileInformation().

`property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given`

### Steps to Reproduce

1. Have a Facebook/Instagram app with invalid credentials (e.g., no app administrators, revoked permissions, or deleted app)
2. Visit any page with craft.craftagram.getInstagramFeed() in the template
3. Site crashes with fatal error
4. Also crashes when trying to access /admin/craftagram/settings/ in the control panel

### Expected Behavior
The plugin should handle API failures gracefully without crashing the site. It should return false/null and optionally log an error.

### Actual Behavior
The page and cp page becomes inaccessible with a fatal PHP error.

PHP version	8.2.29
OS version	Darwin 23.6.0
Database driver & version	MySQL 9.0.1
Image driver & version	Imagick 3.8.0 (ImageMagick 7.1.1-47)
Craft edition & version	Craft Pro 4.15.6.1
Yii version	2.0.52
Twig version	v3.15.0
Guzzle version	7.9.3
Craftagram	4.1.0

**Comment by jsmrtn** [comment]
Fixed 4.2.2

**Comment by S-n-d** [comment]
Hi @jsmrtn i'm still getting an error on 4.2.2

`Undefined property: stdClass::$user_id`

PHP version 8.2.28
MySQL 8.0.40
Imagick 3.8.0 (ImageMagick 6.9.11-60)
Craft Pro 4.16.13
Yii version 2.0.52
Twig version v3.15.0

<img width="969" height="465" alt="Image" src="https://github.com/user-attachments/assets/8520ba13-38bc-4771-921b-dda94a940bc6" />

**Comment by jsmrtn** [comment]
Hopefully 4.2.3 resolves this. I actually can't get this to fail with revoked permissions so I'm flying a bit blind here
